# Example from https://github.com/kewlfft/ansible-aur
- hosts: localhost arch00_root laptop00_root browse_root 

  tasks: 
    - name: Add pacakge through AUR
      
      # Install trizen using makepkg, skip if it is already installed
      aur: name=trizen use=makepkg state=present
      become: yes
      become_user: aur_builder
