# copy zsh, modify zsh
- hosts: main_root vm_root
  # remote_user: insight
  # become_user: root
  # method: sudo

  vars: 
    user: "insight"
    zshrc_config: "/home/{{ user }}/.zshrc"
    zsh_dir: "/home/{{ user }}/.zsh"
    usermod_bin: "/usr/sbin/usermod"
    zsh_shell: "/usr/bin/zsh"

  tasks:
    # Instmain zsh
    #- name: Instmaining zsh (apt)
    #  apt:
    #      name: zsh
    #      state: present
    #  when: ansible_facts["os_family"] == "Debian"

    #- name: Instmaining zsh (pacman)
    #pacman:
    #      name: zsh
    #      state: present
    #  when: ansible_facts["os_family"] == "Archlinux"

    # Copy .zshrc file
    - name: "Copy {{ zshrc_config }} file"
      synchronize: 
        src: "{{ zshrc_config }}"
        dest: "{{ zshrc_config }}"
        mode: pull
    
    # Copy .zsh file
    - name: "Copy {{ zsh_dir }} folder"
      synchronize: 
        src: "{{ zsh_dir }}/"
        dest: "{{ zsh_dir }}/"
        mode: pull

    # Change shell to zsh
    - name: Change shell to zsh
      shell: /usr/sbin/usermod insight -s /usr/bin/zsh 
